### ISSUE TITLE
Please remove global CSS styles from 

### ISSUE THREAD

**Issue by icebob** [mazipan/vue2-simplert#28]
Hi,

great lib, but contains some global CSS styles, which changes my site design if I use it.
```css
html {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -o-box-sizing: border-box;
  -ms-box-sizing: border-box;
  font-size: 62.5%; }

*, *:before, *:after {
  box-sizing: inherit; }
```
I think it is not need to use this lib. 
Btw, it would be good to extract styles to a CSS file.
